### ISSUE TITLE
plugin seems to have problem with sibling and hierarchy together

### ISSUE THREAD

**Issue by bastienJS** [matthiasklan/jquery-top-droppable#1]
Hello Matthias,

I have written you also an email as I am in urgent needs.

I have written a codepen with your plugin having 2 overlapping droppable.

http://codepen.io/anon/pen/OPBXLP

When I drag the elements in the red droppable and drop them on the red droppable they should get reverted INSTEAD the drop event of the orange droppable fires what should not happen.

Using your plugin did not help, a problem seems to be that the top-droppable-id="0" is only set the for the orange droppable, BUT the red droppable does not have this top-droppable attribute.

Any help is really appreciated :-)

Bastien

**Comment by vaceta** [comment]
OK it seems, that my plugin isn't able to handle two different topDroppables. I would suggest to combine the two containers into one topDroppable and do the logic in the drop callback.. here is some sample code. I haven't tested it and the prober logic might be reversed, but I hope it will give you an idea 

```
$(".bothNeedThisClass").topDroppable({
	    drop: function (e, ui) {
	        if(ui.draggable[0].id == 'droppableCurrentCommand' && $(this).attr('id') == 'availableCommandsContainer'){
	        	//do something, maybe trigger false accept (see Documentation of official droppable)
	    	}
	    	if(ui.draggable[0].id == 'droppableAvailableCommand' && $(this).attr('id') == 'currentCommandsContainer'){
	        	//do something, maybe trigger false accept (see Documentation of offical droppable)
	    	}
	    }
	}).droppable({
	    //forget the accept here and do it manually (triggering false accept)
	});
```

**Comment by bastienJS** [comment]
"...combine the two containers into one topDroppable ..."

Looking at "(".bothNeedThisClass").topDroppable({" So I still assume I use TWO droppable? Because I need both.

**Comment by vaceta** [comment]
your two containers have to share a same class (in the example above .bothNeedThisClass). this way when something gets dropped on one of them, the topdroppable drop callback will trigger for the most top one of the containers. And in the drop callback you will write some logic that checks what draggable element ( ui.draggable[0].id   (maybe ui.draggable.attr('id') will work, too)) gets dropped into what container ( $(this).attr('id')). And if it is the wrong combination, you will cancel the dropping and it gets reverted. But the point is, that this time only one drop gets triggered.

**Comment by bastienJS** [comment]
I understand your idea and pointabout the one drop event that gets triggered. But...is your plugin still needed, actually could I not also define these 2 classes on One jquery droppable? Actually also only one drop event should fire right?

**Comment by vaceta** [comment]
hm no on the original jquery droppable two events would be triggered, thats why I developed this plugin in first place. but never tested it with multiple "groups" of topdroppables.

**Comment by vaceta** [comment]
if you look into the code of this plugin, you will see, that this plugin uses the original droppable event and than only returns the one with the smallest z-index of all the events that get triggered

**Comment by bastienJS** [comment]
I changed the codepen with your tips: http://codepen.io/anon/pen/yyRbjJ

But still when I drop the draggable on the top red area it gets dropped because the orange area is beneath it :/ you have any idea? Or do you think it is a bad idea to use the accept function?

**Comment by vaceta** [comment]
hey I think the accept function messes everything up. I modified your implementatio of TopDroppable and now it works (it gets dropped where it has to (see log messages). only the animation of revetring on fail doesn't work. Haven't tried to find a solution, but It has to be something with animate like in this snippet. But as I said. the topDroppable function works now.. just replace your function with this one and test ist

```
  $(".DropMe").topDroppable({    
    
        drop: function (e, ui) {
           alert(ui.draggable[0].id +' dropped on ' + $(this).attr('id') );        
            if( $(this).attr('id') === 'availableCommandsContainer' && $(ui.draggable[0]).hasClass('droppableCurrentCommand') )
           {
             console.log("true");
             //return true;
           }         
        else if( $(this).attr('id') === 'currentCommandsContainer' && $(ui.draggable[0]).hasClass('droppableAvailableCommand'))
           {
             console.log("true");
              //return true;
           }
         else{
           console.log("false");
           ui.draggable.animate(ui.draggable.data().origPosition,"slow");
           //return false;
         }   
        }
    }).droppable({
  });
```

**Comment by vaceta** [comment]
ok the revert animation doesn't work , because the element has not data() option (undefined) you have to save the origin position on dragstart event and than animate it to the position back :)

**Comment by bastienJS** [comment]
Ok thanks so do I see that correctly a "return true/false" in the drop event has no effect. In order to make/imitate a revert behavior I have to animate the invalid drops just back to their original position?

**Comment by bastienJS** [comment]
Thanks for the hint it works now as expect up to 90%: http://codepen.io/helloworld/pen/raqGgz

There is still one little bug. When you drag/drop the draggable over the red area into the paging div with id="available-commands-pager-wrapper" then the draggable gets drop there because the current commands area is beneath that paging div :/

Would it not be a good idea make a 3rd topDroppable with class .DropMe which is the "available-commands-pager-wrapper" and do another check in the drop event the id of the pager div and then revert back?

**Comment by vaceta** [comment]
nice you managed the data() animation! yeah simply make a 3rd check, and that's it :)

**Comment by bastienJS** [comment]
Ok the 3rd topDroppable works fine. Now I just realized a 2nd bug, when I drag/drop the sidebar draggable outside the sidebar but not over any topDroppable area then it is not reverted because the drop event is not fired. Do you know of a good event where the draggable can be reverted where I can check when the div beneath is not class .DropMe to do my revert animation?

**Comment by vaceta** [comment]
you could use the stop event http://api.jqueryui.com/draggable/#event-stop

**Comment by bastienJS** [comment]
Thanks for all your help I move... the discussion now to SO: http://stackoverflow.com/questions/29007944/get-element-of-having-certain-class-which-i-hover-in-the-draggable-stop-event

Maybe you have an idea :-)

**Comment by bastienJS** [comment]
I just realized that using 3 top droppable now having a z-index I am now not anymore able to drag an orange element OVER the sidebar its always beneath the sidebar. But I see no chance in changing z-index dynamically because when the sidebar has a lower z-index as the orange area the dragging over looks fine but the sidebar is beneath the orange area LOL, you have any idea?

Else I have to revert the top-droppable :/

**Comment by vaceta** [comment]
hm I think you must get the draggable orange div out of the container parent, so you can asign him an own high z-index ( > 200 )

**Comment by bastienJS** [comment]
But then the orange div will overlap the sidebar. I think that is a technical problem here not solvable. Either the orange div has a higher z-index than sidebar => drag over to sidebar looks good.
Or the sidebar div has a highter z-index than orange div => sidebar is over the orange div opened

I see no solution its a technical/usability constraint.

**Comment by bastienJS** [comment]
I got it: http://codepen.io/helloworld/pen/JomZMr

I removed your top-droppable because of the index fighting. So I can drag/drop on each side with each item. I used your approach with the droppable on class name because my sidebar are 3 droppable now HAHA. Revert works still fine. Hell I am glad and still gratefull because you pushed me in the right direction ;-)
